### ISSUE TITLE
Asset file names do not match reference in files (ex. roundCard)

### ISSUE THREAD

**Issue by justinHe123** [hubert94536/ChickenTinder#134]

**Comment by icevin** [comment]
Can you elaborate more on what this means? Sorry

**Comment by justinHe123** [comment]
ex. image in the asset folder is called "indian.png", but is referenced in code as "Indian.jpg" (with capitalization) causing compile issues

note these issues were already fixed with the latest push, but it might be a good idea to standardize file naming conventions for the future

**Comment by hubert94536** [comment]
Yes justin is correct, we need to be more consistent for naming which I've included in onboarding doc
